# Generated by Django 5.2.5 on 2025-08-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_grupo", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="grupos_participantes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
