# Generated by Django 4.2.23 on 2025-08-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_despesa_data_despesa_renda_metapessoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='core.metapessoal')),
            ],
        ),
    ]
