# Generated by Django 4.2.23 on 2025-08-19 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_depositometa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastofixo',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='gastofixo',
            name='data_vencimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
