# Generated by Django 4.2.23 on 2025-08-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_renda_data_metagrupo_contribuicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoGastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('gasto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.gastofixo')),
            ],
        ),
    ]
