# Generated by Django 4.2.23 on 2025-08-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagamentogastofixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentogastofixo',
            name='gasto_fixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='core.gastofixo'),
        ),
    ]
