# Generated by Django 4.2.23 on 2025-08-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagamentogastofixo_descricao_pagamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuicao',
            old_name='valor',
            new_name='valor_contribuicao',
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='descricao_contribuicao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='meta_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to='core.metagrupo'),
        ),
        migrations.AlterField(
            model_name='metagrupo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='core.grupo'),
        ),
    ]
