# Generated by Django 4.2.23 on 2025-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_valor_contribuicao_valor_contribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamentogastofixo',
            name='categoria',
            field=models.CharField(choices=[('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
