# Generated by Django 4.2.23 on 2025-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_despesa_categoria_pagamentogastofixo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentogastofixo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='gastofixo',
            name='categoria',
            field=models.CharField(choices=[('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
