# Generated by Django 4.2.23 on 2025-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pagamentogastofixo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentogastofixo',
            name='categoria_pagamento',
            field=models.CharField(choices=[('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
